### ISSUE TITLE
Failed to launch daily image by alias "devel"

### ISSUE THREAD

**Issue by khfeng** [CanonicalLtd/multipass#1176]
$ multipass find
Image                   Aliases           Version          Description
...
daily:20.04             devel,focal       20191029         Ubuntu 20.04 LTS

$ multipass launch --name devel devel
launch failed: Unable to find an image matching "devel"
$ multipass launch --name focal focal
launch failed: Unable to find an image matching "focal"

$ multipass launch --name devel daily:20.04
Launched: devel

**Comment by townsend2010** [comment]
Hi @khfeng,

I know it's not intuitive, but the proper way to launch an instance via `devel` is to use `daily:devel`.   The `daily` "remote" has to be specified in this case, otherwise it will default to the "release" remote and, well, `devel` is not released yet :grin:

Please let us know if this works for you.

**Comment by khfeng** [comment]
Yes it works for me :) Good to know it's not a bug.

It'll be great if there's a hint to let users know "daily:devel" should be used.
