### ISSUE TITLE
user consistency with lxd

### ISSUE THREAD

**Issue by sergiusens** [CanonicalLtd/multipass#219]
I know this is not lxd, but some consistency would be nice:
```
sergiusens@mirkwood:~$ lxc exec snapcraft-xenial-dev -- whoami
root
sergiusens@mirkwood:~$ multipass exec assertive-mouflon -- whoami
ubuntu
```

**Comment by Saviq** [comment]
I'm not sure we'll reach consistency with this, we might switch away from the `ubuntu` user, to `multipass` or, preferably `$USER`, but we're likely to continue logging in to the instance as a user, not root. We're relying on cloud-init inside the instance so we can ask it to create the user as we please.

Relatedly, [LXD will keep logging in as root](https://github.com/lxc/lxd/issues/4233), because they don't have the luxury to rely on cloud-init, but they do have the luxury of a TTY that multipass does not.
