### ISSUE TITLE
Hide instances from general view

### ISSUE THREAD

**Issue by sergiusens** [CanonicalLtd/multipass#348]
It would be great if we could tag instances so they are not seen from a general `multipass list` call and identify them as an implementation detail for another project (i.e.; snapcraft) to identify ownership and not meddle with instances that do not belong to the handling project or clash with those created by a user interacting with the multipass cli directly

**Comment by townsend2010** [comment]
We'll provide a hidden option to `launch` called, wait for it, `--hidden` and this will hide the instance in `list` accept if `--all` is passed into the `list` command.

**Comment by townsend2010** [comment]
As I'm working on this, I'm not sure of the real goal of "hiding" an instance.  Sure, we can not show it in a general `multipass list` command, but we'll have an `--all` option to list that will then show it.  And the `--all` option will show up in `list`'s help, making it fairly easy to the user on how to discover hidden instances, so how hidden is the instance?

Is the goal to generally not allow any manipulation of the hidden instance outside of the consumer of the instance?  Let's discuss this further so we can implement this correctly for the goal we want to achieve.

**Comment by ricab** [comment]
The effect of `--all` in other commands would also have to be considered.

**Comment by townsend2010** [comment]
Yeah, we need some discussion on the design of this.  Perhaps using `--hidden` for every command to work on hidden instances instances is better.  But even then, that's quite easily discoverable, so I'm just wondering if this is all worth the effort.  Just need some feedback from @sergiusens on what his end goal is for this.

**Comment by sergiusens** [comment]
Personally, I would prefer a design that looks more like `lxd project` and the entire idea behind this request from my side is to assign VM instance ownership. Hiding seems to be the thought as the quickest approach to achieve something that would avoid most user errors, but the end goal is ownership more than not being able to see it.

**Comment by townsend2010** [comment]
@sergiusens,

Yeah, something like projects would be nice, but as you allude to, that's not going to be a quick route.  So with something like "hidden" instances, how hidden are you wanting them to be?  Like just not show up in the normal `multipass list` or something more like making the user add `--hidden` to any command that manipulates or views the instance.

For example, say we add a new `--hidden` option to launch and that instance is now marked at "hidden".  So `multipass list` will not display that hidden instance, but `multipass list --hidden` will show that instance along with other non-hidden instances, if any.

Then the question of whether something like `multipass shell my-hidden-container` works or would we require something like `multipass shell my-hidden-container --hidden` in order for a user to shell into the container?

**Comment by Saviq** [comment]
I wouldn't add `--hidden` to our CLI since then we'd have to live with it... I'd make this a _hidden_ feature in that if someone (something) names an instance using a `<prefix>:` (e.g. `snapcraft:multipass`), it will not be shown in `multipass list`, unless `--all` is given.

Question is whether `--all` in other commands should act on those... I'd like `multipass delete --purge --all` to continue to clean my slate, and I suppose any project that uses this should know better as to not put any valuable data inside those instances...

Then again, `multipass start --all` and potentially dozens of `snapcraft:<project>` instances get started...

I'm not sure I'm liking any shortcut for this. Even projects... @sergiusens you mention ownership, but the user is still the owner of them, hiding them might just make them annoyed that things are taking space and they don't know where and why...

**Comment by Saviq** [comment]
I'll close this as won't fix, we don't want to hide things from the user.
