### ISSUE TITLE
multipass delete causes network manager to raise a notification

### ISSUE THREAD

**Issue by sergiusens** [CanonicalLtd/multipass#409]
When deleting an instance, network manager raises a notification about the network going down. It is a rather confusing thing from an end users point of view.

**Comment by townsend2010** [comment]
Yeah, this seems like something new in Network Manager where it throws up a notification on *any* network event.  We do delete the associated tap network device when an instance is deleted, which is the right thing to do since we don't want to leave around dangling network devices.  This will require investigation in Network Manager (and possibly adding a bug report for this there) to see if there is anything we can to mitigate this.

**Comment by Saviq** [comment]
I think another reason for this is that we actually ship Qt's networking bits that interrogate NetworkManager (you can see messages about it trying to connect over dbus). We'll get rid of those when going to `strict` confinement, so that could go away.

**Comment by townsend2010** [comment]
I don't think this is an issue anymore, so closing.  We can reopen if it shows up again.
