### ISSUE TITLE
Make default user "ubuntu"

### ISSUE THREAD

**Issue by kstenerud** [CanonicalLtd/multipass#469]
An enhancement request:

Make the default user "ubuntu" rather than "multipass" to keep uniformity between virtualization & container launcher technologies. It makes it easier to swap one implementation for another (such as in a script) if you don't have to also keep track of what user it auto-creates.

**Comment by pekof** [comment]
User multipass is used so user name don't depend on distribution.
What user would you use on Fedora

**Comment by kstenerud** [comment]
True, but it would definitely be nice to work out some common default user name with other virtualization projects, as it will make scripting less of a hassle...

**Comment by townsend2010** [comment]
Hi @kstenerud,

Thanks for the report.  As @pekof noted, we chose to use `multipass` as the default user because of wanting to support other distributions.

That said, if you need a new user added in the instance, you can pass `launch` a custom cloud-init configuration which sets a new user.  The default user is really used by `multipass` internally for the `shell`/`exec`/`mount` commands.

**Comment by kstenerud** [comment]
Great! Thanks!

**Comment by Saviq** [comment]
There should be no reason for your scripts to rely on the username. You can use `$HOME` and `$USER` and other environment variables. Also, all relevant Multipass commands work relative to `$HOME` in the first place.
