### ISSUE TITLE
Cryptic error message if VirtualBox is running

### ISSUE THREAD

**Issue by igorljubuncic** [CanonicalLtd/multipass#475]
Multipass does not launch with VirtualBox running on the system.

multipass launch
failed to launch: ioctl(KVM_CREATE_VM) failed: 16 Device or resource busy
failed to initialize KVM: Device or resource busy

The error message is ambiguous and should more clearly explain to the user the source of the problem and how to rectify it (stop VirtualBox processes, terminate VirtualBox, etc).

Tested on:

Ubuntu 18.04.1
multipass  2018.10.1
multipassd 2018.10.1

**Comment by townsend2010** [comment]
Hi @igorljubuncic,

Thanks for entering this report.  This already known is being tracked in #6.

The problem is that this error is coming from kvm itself and we just display the error as it is.  We previously discussed doing some sort of error string matching and then translate that into a different error message, but this is fragile in that if kvm changes their error message in any way, we will no longer match the error string and there will be another cryptic error message.
