### ISSUE TITLE
CA Certificate Location

### ISSUE THREAD

**Issue by bketelsen** [CanonicalLtd/multipass#571]
I used the multipass proto file to generate a Go grpc client so I could write my own frontend for multipass, however I can't seem to connect with GRPC because it needs the CA that generated the certificates.  I've searched my hard drive, but came up empty. Where is the CA store?

Thanks!

**Comment by Saviq** [comment]
By design it shouldn't require a certificate from the same CA, rather any certificate you provide (self-signed are fine, too). There is some missing functionality around this though, so it should be possible to use the key and certificate created by our client. The file is normally called `localhost_key.pem`.

See https://github.com/CanonicalLtd/multipass/blob/master/src/cert/ssl_cert_provider.cpp for the code used to generate it.

**Comment by bketelsen** [comment]
Odd.  I've tried the cert generated by the daemon and the one the cli tool appears to be using and both give the same error.

```
2019/01/23 13:16:11 List Errorrpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority"
```
I'll try generating my own and see if that gets me anywhere.  Thanks for the reply!
