### ISSUE TITLE
initial cloud boot with Windows 10 multipath takes much longer than subsequent boots

### ISSUE THREAD

**Issue by ColinIanKing** [CanonicalLtd/multipass#712]
Using a Xenial cloud image on a Windows 10 Pro Xeon desktop the initial boot takes a long time.  Using systemd-analyze on the first boot it is observed that cloud-final.service is taking 1minute 30 seconds during the boot:    

```
1min 30.052s cloud-final.service
          8.582s pollinate.service
          6.906s cloud-init-local.service
          4.303s keyboard-setup.service
          4.239s dev-sda1.device
          3.375s cloud-init.service
          2.931s lxd-containers.service
          2.575s networkd-dispatcher.service
          2.549s snapd.service
          1.942s apparmor.service
          1.782s snapd.seeded.service
          1.377s ebtables.service
          1.366s cloud-config.service
          1.362s lvm2-monitor.service
```
 ...etc

...however on subsequent boots this is no longer the issue:

```
          9.447s cloud-final.service
          4.326s cloud-init-local.service
          4.226s snapd.seeded.service
          3.200s dev-sda1.device
          2.444s cloud-init.service
          2.278s snapd.service
          2.064s console-setup.service
          1.890s cloud-config.service
          1.833s lxd-containers.service
          1.687s pollinate.service
          1.587s apparmor.service
          1.083s accounts-daemon.service
```

..etc

This should be investigated further.  On other virtual machines this does not occur (e.g. Linux using KVM QEMU) the cloud image does not do this.

**Comment by townsend2010** [comment]
@ColinIanKing,

Hi, this is will no longer occur with the next beta release which should hopefully be released today.  The issue is that we were previously seeding `sshfs` in cloud-init, which depending on network conditions, can add quite a bit of time due `apt cache` updates and downloading `sshfs`.  The new beta release removes the `sshfs` seeding and only installs it once someone defines a mount.

The archive seems particularly slow today, so this is probably why you are noticing this.

**Comment by ColinIanKing** [comment]
Thanks!
