### ISSUE TITLE
execute multipass shell without instance name create a new instanced 

### ISSUE THREAD

**Issue by Fred78290** [CanonicalLtd/multipass#868]
Hi after upgrading my multipass on MacOS from 0.70 to 0.71, by inadvertently
I ran these command

MACBOOKPRO:~ Me$ multipass launch 
Launched: calming-lobster                                                       
MACBOOKPRO:~ fboltz$ multipass shell
Launched: primary                                                               
So multipass shell started a new instance instead throw an error

**Comment by ricab** [comment]
Hi there. This is as expected. `multipass shell` without an instance name defaults to the `primary` instance, and will create it if it is not around yet. If you want to attach to your other instance, use `multipass shell calming-lobster` instead. See `multipass help shell` for more info.

**Comment by ricab** [comment]
Hi there. This is as expected. `multipass shell` without an instance name defaults to the `primary` instance, and will create it if it is not around yet. If you want to attach to your other instance, use `multipass shell calming-lobster` instead. See `multipass help shell` for more info.

**Comment by Fred78290** [comment]
I don't agree with your predicate. The help command say that

  shell     **Open a shell on a running instance**

So If I messed to precise an instance name, the command must return an error telling "missing argument".

**Comment by townsend2010** [comment]
Hi @Fred78290,

I believe you are referring to the output of `multipass help`, correct?  That is just a very brief, high level overview of all of the particular `multipass` commands.

For a much better usage explanation of each command, you can use `multipass <command> -h`.  For `shell`, it explains what happens if you omit the instance name when issuing `multipass shell`.  If you do try using an instance name there and misspell it, it will error out saying the instance does not exist.

I hope this explains it a little better and sorry for any confusion.

**Comment by Fred78290** [comment]
Hum, It's so british as answer....

Logically in the past "multipass shell" omitting the instance name returned an error "I'm sorry Dave, I can't do that..."

If I do a parallel with ssh command, I don't precise my host target, the ssh command will not create for me a virtual machine to satisfy my request....

I understand the principle to create an instance at the demand like a docker run but in this case create a command multipass run. I'll be happy :)

For me and as expected in the past "shell" means launch a bash on .... In pasted release it was multipass connect.

Take a look on my public GitHub repositories that i do with multipass.

Regards
