### ISSUE TITLE
snap: Run check_kvm_support during install

### ISSUE THREAD

**Issue by townsend2010** [CanonicalLtd/multipass#977]
When installing the Multipass snap package, the `check_kvm_support` script should run to detect if the system is capable of running KVM.  If the script fails, it should display the error to the user then.  This should lead to a better user experience in that the user won't have to wait to run `multipass launch` in order to find out their system is incapable of running KVM.

Any opinions?

**Comment by Saviq** [comment]
The problem is the only option we have there is failing the install. And what if the user wanted to use a remote Multipass instance?

**Comment by townsend2010** [comment]
@Saviq,

Ok, yes that's true for _whenever_ we support remote Multipass.  So if that is the case, then I think the OSX installer shouldn't fail install if `kern.hv_support` is not set since that is the same idea.

**Comment by Saviq** [comment]
I think that the best we can do in the installer is to inform the user what they'll need to do before they can use Multipass locally. We won't be able to do that in the snap, since there's no feedback that we can give other than failing the install.

This, IMO (at least on Mac and Windows) gives the user a choice - proceed with the install and fulfill the requirements later, or cancel the installation. Bailing means they have to fulfill the requirements and then restart the installation, potentially re-downloading the installer if they ran it straight from the browser.

Even better, where we can, we should offer the option to fulfill the requirements for them (like installing Hyper-V, if possible and is the user's preference).

**Comment by townsend2010** [comment]
Ok, sounds like doing the check during snap install is not the way to go.  Closing.
